# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Segmentation sémantique en temps réel à partir d’un nano-ordinateur : étude des performances et des limites
description: Essai de recherche en géomatique appliquée dans le cadre de la Maîtrise en géographie, cheminement géodéveloppement durable; (2020)
github_username: vince7lf

# Email and twitter are optional:
email: vincent.lefalher@usherbrooke.ca
twitter_username: 

# OPTIONAL: override baseurl and url if using a custom domain
#url:  the base hostname & protocol for your site, e.g. http://example.com
#baseurl: the subpath of your site, e.g. /blog

# Set this to true to get LaTeX math equation support
use_math: 

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
